package hello;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        Minimize = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        login = new javax.swing.JLabel();
        adm_pwdtxt = new javax.swing.JPasswordField();
        adm_nametxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(199, 0, 57));
        jPanel2.setToolTipText("");
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel2.setLayout(null);

        Minimize.setBackground(new java.awt.Color(0, 0, 0));
        Minimize.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Minimize.setForeground(new java.awt.Color(153, 153, 153));
        Minimize.setText("_");
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.setFocusPainted(false);
        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });
        jPanel2.add(Minimize);
        Minimize.setBounds(710, 0, 43, 25);

        Close.setBackground(new java.awt.Color(0, 0, 0));
        Close.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Close.setForeground(new java.awt.Color(153, 153, 153));
        Close.setText("X");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.setFocusPainted(false);
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel2.add(Close);
        Close.setBounds(750, 0, 45, 25);

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_button.png"))); // NOI18N
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginMouseReleased(evt);
            }
        });
        jPanel2.add(login);
        login.setBounds(550, 400, 130, 70);

        adm_pwdtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adm_pwdtxt.setForeground(new java.awt.Color(88, 24, 69));
        adm_pwdtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        adm_pwdtxt.setBorder(null);
        adm_pwdtxt.setOpaque(false);
        adm_pwdtxt.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(adm_pwdtxt);
        adm_pwdtxt.setBounds(480, 300, 230, 30);

        adm_nametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adm_nametxt.setForeground(new java.awt.Color(88, 24, 69));
        adm_nametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        adm_nametxt.setToolTipText("");
        adm_nametxt.setBorder(null);
        adm_nametxt.setOpaque(false);
        jPanel2.add(adm_nametxt);
        adm_nametxt.setBounds(480, 210, 230, 30);

        jLabel1.setFont(new java.awt.Font("abeatbyKai", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Id");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(350, 210, 95, 32);

        jLabel3.setFont(new java.awt.Font("abeatbyKai", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(350, 290, 121, 53);

        jLabel4.setFont(new java.awt.Font("abeatbyKai", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin Login");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(410, 70, 230, 43);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(480, 240, 240, 10);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(480, 330, 240, 10);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setToolTipText("");
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(290, 110, 17, 397);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin-icon1.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 170, 257, 249);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminback.jpg"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel5.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel5.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 600);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
       
        mysqlconnector msq=new mysqlconnector();
        try
        {
                Connection con=msq.getConnection();
                    PreparedStatement pst=con.prepareStatement("select admin_name , admin_pwd from admin where admin_name=? and admin_pwd=?");
                    String admin_name=adm_nametxt.getText();
                    pst.setString(1,admin_name);
                    pst.setString(2,new String(adm_pwdtxt.getPassword()));
                    ResultSet rs=pst.executeQuery();
                    if(rs.next())
                    {
                        mysqlconnector msq1=new mysqlconnector();
                        try
                        {
                            Connection con1= msq1.getConnection();
                            PreparedStatement pst1=con1.prepareStatement("update admin set admin_status=1 where admin_name='"+admin_name+"';");
                            pst1.executeUpdate();
                        }
                        catch(Exception e)
                        {}
                
                        
                        JOptionPane.showMessageDialog(this, "Logged in Successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                        
                        new adminhome(admin_name).setVisible(true);
                        this.dispose();
                            
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Invalid Credentials", "Error", JOptionPane.ERROR_MESSAGE);
                    }
        }
        catch(Exception e)
        {
              e.printStackTrace();
        }
         
    }//GEN-LAST:event_loginMouseClicked

    private void loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMousePressed
        // TODO add your handling code here:
            //    Image ii=new ImageIcon(getClass().getResource("/images/button_loginpressed.png")).getImage();
            // login.setIcon(new ImageIcon(ii));
     
    }//GEN-LAST:event_loginMousePressed

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        // TODO add your handling code here:
        //Image ii=new ImageIcon(getClass().getResource("/images/button_login_hover_1.png")).getImage();
          //   login.setIcon(new ImageIcon(ii));
       
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        // TODO add your handling code here:
        //Image ii=new ImageIcon(getClass().getResource("/images/button_login_1.png")).getImage();
          //   login.setIcon(new ImageIcon(ii));
       
    }//GEN-LAST:event_loginMouseExited

    private void loginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseReleased
          //Image ii=new ImageIcon(getClass().getResource("/images/button_login_1.png")).getImage();
            // login.setIcon(new ImageIcon(ii));
    }//GEN-LAST:event_loginMouseReleased

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        this.setState(admin.ICONIFIED);
    }//GEN-LAST:event_MinimizeActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        System.exit(0);
        //this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton Minimize;
    private javax.swing.JTextField adm_nametxt;
    private javax.swing.JPasswordField adm_pwdtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel login;
    // End of variables declaration//GEN-END:variables
}
