package hello;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class adminmovie extends javax.swing.JFrame {

     String adm;
   
    public adminmovie() {
        initComponents();
                
        add.setVisible(false);
        update.setVisible(false);
        del.setVisible(false);
        search.setVisible(true);
        
        searchradio.setSelected(true);
        
        if(searchradio.isSelected()==true)
        {
            searchradio.setSelected(true);
         del.setVisible(false);
        add.setVisible(false);
        update.setVisible(false);
        search.setVisible(true);
        
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(true);
        jSeparator3.setVisible(false);
        jSeparator4.setVisible(false);
        
        mid.setVisible(false);
        mname.setVisible(true);
        descr.setVisible(false);
        rating.setVisible(false);
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(true);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        }
        
        String n,d;
        int r,m;
        mysqlconnector msq=new mysqlconnector();
        try {
            DefaultTableModel model=(DefaultTableModel) Table.getModel();
        
            Connection con=msq.getConnection();
            PreparedStatement pst=con.prepareStatement("select * from Movie ");
           
           
            ResultSet rs=pst.executeQuery();
            while(rs.next())
            {
                m=rs.getInt("mov_id");
                n=rs.getString("mov_name");
                d=rs.getString("descr");
                 r=rs.getInt("rating");
               model.addRow(new Object[]{m,n,d,r});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     
    public adminmovie(String adm_nm) {
        initComponents();
        adm=adm_nm;
        
        Current_admin.setText(adm);
        
        add.setVisible(false);
        update.setVisible(false);
        del.setVisible(false);
        search.setVisible(true);
        
        searchradio.setSelected(true);
        
        if(searchradio.isSelected()==true)
        {
            searchradio.setSelected(true);
         del.setVisible(false);
        add.setVisible(false);
        update.setVisible(false);
        search.setVisible(true);
        
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(true);
        jSeparator3.setVisible(false);
        jSeparator4.setVisible(false);
        
        mid.setVisible(false);
        mname.setVisible(true);
        descr.setVisible(false);
        rating.setVisible(false);
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(true);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        }
        
        String n,d;
        int r,m;
        mysqlconnector msq=new mysqlconnector();
        try {
            DefaultTableModel model=(DefaultTableModel) Table.getModel();
        
            Connection con=msq.getConnection();
            PreparedStatement pst=con.prepareStatement("select * from Movie ");
           
           
            ResultSet rs=pst.executeQuery();
            while(rs.next())
            {
                m=rs.getInt("mov_id");
                n=rs.getString("mov_name");
                d=rs.getString("descr");
                 r=rs.getInt("rating");
               model.addRow(new Object[]{m,n,d,r});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Admin_logo = new javax.swing.JLabel();
        Current_admin = new javax.swing.JLabel();
        Logout_Lbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Tableheading = new javax.swing.JLabel();
        SearchResultTable = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        back_lbl = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        descr = new javax.swing.JTextField();
        rating = new javax.swing.JTextField();
        search = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        del = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        addradio = new javax.swing.JRadioButton();
        updateradio = new javax.swing.JRadioButton();
        delradio = new javax.swing.JRadioButton();
        searchradio = new javax.swing.JRadioButton();
        backgroundImage = new javax.swing.JLabel();
        Minimize = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("abeatbyKai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Result");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(860, 450, 430, 46);

        Admin_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Admin.png"))); // NOI18N
        jPanel1.add(Admin_logo);
        Admin_logo.setBounds(1290, 70, 50, 50);

        Current_admin.setBackground(new java.awt.Color(51, 51, 51));
        Current_admin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Current_admin.setForeground(new java.awt.Color(255, 255, 255));
        Current_admin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Current_admin.setMaximumSize(new java.awt.Dimension(200, 30));
        Current_admin.setMinimumSize(new java.awt.Dimension(200, 30));
        Current_admin.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(Current_admin);
        Current_admin.setBounds(1080, 80, 200, 30);

        Logout_Lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Logout_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Logout_Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoutbutton.png"))); // NOI18N
        Logout_Lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout_Lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_LblMouseClicked(evt);
            }
        });
        jPanel1.add(Logout_Lbl);
        Logout_Lbl.setBounds(1200, 110, 100, 50);

        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1230, 10, 30, 20);

        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1290, 10, 30, 20);

        Tableheading.setFont(new java.awt.Font("abeatbyKai", 1, 24)); // NOI18N
        Tableheading.setForeground(new java.awt.Color(255, 255, 255));
        Tableheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tableheading.setText("Admin Page Movie Management");
        jPanel1.add(Tableheading);
        Tableheading.setBounds(360, 30, 580, 46);

        SearchResultTable.setFont(new java.awt.Font("abeatbyKai", 1, 24)); // NOI18N
        SearchResultTable.setForeground(new java.awt.Color(255, 255, 255));
        SearchResultTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SearchResultTable.setText("Movie Table");
        jPanel1.add(SearchResultTable);
        SearchResultTable.setBounds(870, 150, 430, 46);

        Table1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie ID", "Movie Name", "Description", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Table1.setGridColor(new java.awt.Color(255, 255, 255));
        Table1.getTableHeader().setResizingAllowed(false);
        Table1.getTableHeader().setReorderingAllowed(false);
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(840, 490, 490, 190);

        Table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie ID", "Movie Name", "Description", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.getTableHeader().setResizingAllowed(false);
        Table.getTableHeader().setReorderingAllowed(false);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(840, 190, 490, 240);

        back_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_button.png"))); // NOI18N
        back_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_lblMouseClicked(evt);
            }
        });
        jPanel1.add(back_lbl);
        back_lbl.setBounds(60, 50, 160, 100);

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("abeatbyKai", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Movie ID");

        jLabel3.setFont(new java.awt.Font("abeatbyKai", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Movie Name");

        jLabel4.setFont(new java.awt.Font("abeatbyKai", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description");

        jLabel5.setFont(new java.awt.Font("abeatbyKai", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rating");

        mid.setFont(new java.awt.Font("abeatbyKai", 0, 12)); // NOI18N
        mid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mid.setText("Enter Movie ID");
        mid.setToolTipText("");
        mid.setAlignmentX(2.0F);
        mid.setBorder(null);
        mid.setMaximumSize(new java.awt.Dimension(230, 30));
        mid.setMinimumSize(new java.awt.Dimension(230, 30));
        mid.setOpaque(false);
        mid.setPreferredSize(new java.awt.Dimension(230, 30));
        mid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                midMouseClicked(evt);
            }
        });
        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });

        mname.setFont(new java.awt.Font("abeatbyKai", 0, 12)); // NOI18N
        mname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mname.setText("Enter Movie Name");
        mname.setBorder(null);
        mname.setMaximumSize(new java.awt.Dimension(230, 30));
        mname.setMinimumSize(new java.awt.Dimension(230, 30));
        mname.setOpaque(false);
        mname.setPreferredSize(new java.awt.Dimension(230, 30));
        mname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnameMouseEntered(evt);
            }
        });

        descr.setFont(new java.awt.Font("abeatbyKai", 0, 12)); // NOI18N
        descr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        descr.setText("Enter Description");
        descr.setBorder(null);
        descr.setMaximumSize(new java.awt.Dimension(230, 30));
        descr.setMinimumSize(new java.awt.Dimension(230, 30));
        descr.setOpaque(false);
        descr.setPreferredSize(new java.awt.Dimension(230, 30));
        descr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descrMouseClicked(evt);
            }
        });
        descr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descrActionPerformed(evt);
            }
        });

        rating.setFont(new java.awt.Font("abeatbyKai", 0, 12)); // NOI18N
        rating.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rating.setText("Enter Rating");
        rating.setBorder(null);
        rating.setMaximumSize(new java.awt.Dimension(230, 30));
        rating.setMinimumSize(new java.awt.Dimension(230, 30));
        rating.setOpaque(false);
        rating.setPreferredSize(new java.awt.Dimension(230, 30));
        rating.setVerifyInputWhenFocusTarget(false);
        rating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingMouseClicked(evt);
            }
        });
        rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingActionPerformed(evt);
            }
        });

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_button.png"))); // NOI18N
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updatebutton.png"))); // NOI18N
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_button.png"))); // NOI18N
        del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delMouseClicked(evt);
            }
        });

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_button.png"))); // NOI18N
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setMaximumSize(new java.awt.Dimension(240, 10));
        jSeparator1.setMinimumSize(new java.awt.Dimension(240, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(240, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setMaximumSize(new java.awt.Dimension(240, 10));
        jSeparator2.setMinimumSize(new java.awt.Dimension(240, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(240, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setMaximumSize(new java.awt.Dimension(240, 10));
        jSeparator3.setMinimumSize(new java.awt.Dimension(240, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(240, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setMaximumSize(new java.awt.Dimension(240, 10));
        jSeparator4.setMinimumSize(new java.awt.Dimension(240, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(240, 10));

        addradio.setBackground(new java.awt.Color(199, 0, 57));
        buttonGroup1.add(addradio);
        addradio.setFont(new java.awt.Font("abeatbyKai", 0, 14)); // NOI18N
        addradio.setForeground(new java.awt.Color(255, 255, 255));
        addradio.setText("ADD");
        addradio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addradio.setOpaque(false);
        addradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addradioActionPerformed(evt);
            }
        });

        updateradio.setBackground(new java.awt.Color(199, 0, 57));
        buttonGroup1.add(updateradio);
        updateradio.setFont(new java.awt.Font("abeatbyKai", 0, 14)); // NOI18N
        updateradio.setForeground(new java.awt.Color(255, 255, 255));
        updateradio.setText("UPDATE");
        updateradio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateradio.setOpaque(false);
        updateradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateradioActionPerformed(evt);
            }
        });

        delradio.setBackground(new java.awt.Color(199, 0, 57));
        buttonGroup1.add(delradio);
        delradio.setFont(new java.awt.Font("abeatbyKai", 0, 14)); // NOI18N
        delradio.setForeground(new java.awt.Color(255, 255, 255));
        delradio.setText("DELETE");
        delradio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delradio.setOpaque(false);
        delradio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delradioMouseClicked(evt);
            }
        });
        delradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delradioActionPerformed(evt);
            }
        });

        buttonGroup1.add(searchradio);
        searchradio.setFont(new java.awt.Font("abeatbyKai", 0, 14)); // NOI18N
        searchradio.setForeground(new java.awt.Color(255, 255, 255));
        searchradio.setText("SEARCH");
        searchradio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchradio.setOpaque(false);
        searchradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchradioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59)
                                .addComponent(descr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(114, 114, 114)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(update)
                                .addGap(41, 41, 41)
                                .addComponent(del))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(searchradio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(addradio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(updateradio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(delradio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchradio)
                            .addComponent(addradio)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(delradio)
                                .addComponent(updateradio)))
                        .addGap(47, 47, 47)
                        .addComponent(mid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(del, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        jPanel1.add(panel1);
        panel1.setBounds(50, 190, 720, 510);

        backgroundImage.setBackground(new java.awt.Color(255, 255, 255));
        backgroundImage.setForeground(new java.awt.Color(255, 255, 255));
        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin backgroundlarge1.png"))); // NOI18N
        jPanel1.add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1360, 770);

        Minimize.setBackground(new java.awt.Color(0, 0, 0));
        Minimize.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Minimize.setForeground(new java.awt.Color(153, 153, 153));
        Minimize.setText("_");
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.setFocusPainted(false);
        Minimize.setOpaque(false);
        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(Minimize);
        Minimize.setBounds(1220, 10, 43, 25);

        Close.setBackground(new java.awt.Color(0, 0, 0));
        Close.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Close.setForeground(new java.awt.Color(153, 153, 153));
        Close.setText("X");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.setFocusPainted(false);
        Close.setOpaque(false);
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel1.add(Close);
        Close.setBounds(1290, 10, 45, 25);

        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(730, 390, 170, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    void showtabledata()
    {
     
        String n,d;
        int r,m;
        mysqlconnector msq=new mysqlconnector();
        try {
            DefaultTableModel model=(DefaultTableModel) Table.getModel();
        
            Connection con=msq.getConnection();
            PreparedStatement pst=con.prepareStatement("select * from Movie ");
           
           
            ResultSet rs=pst.executeQuery();
            while(rs.next())
            {
                m=rs.getInt("mov_id");
                n=rs.getString("mov_name");
                d=rs.getString("descr");
                 r=rs.getInt("rating");
               model.addRow(new Object[]{m,n,d,r});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    
    }
    private void addradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addradioActionPerformed
        // TODO add your handling code here:
               if(addradio.isSelected()==true)
        {
            addradio.setSelected(true);
         del.setVisible(false);
        add.setVisible(true);
        update.setVisible(false);
        search.setVisible(false);
        
        jSeparator1.setVisible(true);
        jSeparator2.setVisible(true);
        jSeparator3.setVisible(true);
        jSeparator4.setVisible(true);
        
        mid.setVisible(true);
        mname.setVisible(true);
        descr.setVisible(true);
        rating.setVisible(true);
        
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        }
        mid.setText("");
        mname.setText("");
        descr.setText("");
        rating.setText("");
    }//GEN-LAST:event_addradioActionPerformed

    private void updateradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateradioActionPerformed
        // TODO add your handling code here:
                   if(updateradio.isSelected()==true)
        {
            updateradio.setSelected(true);
         del.setVisible(false);
        add.setVisible(false);
        update.setVisible(true);
        search.setVisible(true);
        
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(true);
        jSeparator3.setVisible(true);
        jSeparator4.setVisible(true);
        
        mid.setVisible(false);
        mname.setVisible(true);
        descr.setVisible(true);
        rating.setVisible(true);
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        }
        mid.setText("");
        mname.setText("");
        descr.setText("");
        rating.setText("");
    }//GEN-LAST:event_updateradioActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) Table.getModel();
        mid.setText(model.getValueAt(Table.getSelectedRow(), 0).toString());
        mname.setText(model.getValueAt(Table.getSelectedRow(), 1).toString());
        descr.setText(model.getValueAt(Table.getSelectedRow(), 2).toString());
        rating.setText(model.getValueAt(Table.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
       
        
        String mov_id=mid.getText();
        mysqlconnector msq=new mysqlconnector();
        try {
            Connection con=msq.getConnection();
            String m_search;
            m_search=mname.getText();
            
            if(!m_search.equals("") && !m_search.equals("Enter Movie Name"))
            {
                PreparedStatement pst=con.prepareStatement("select * from Movie where mov_name like '"+m_search+"%';");
                //pst.setString(1, mov_id);
                DefaultTableModel model=(DefaultTableModel) Table1.getModel();
                model.setRowCount(0);
                String n,d;
                int r,m;
                ResultSet rs=pst.executeQuery();
                while(rs.next())
                {
                    m=rs.getInt("mov_id");
                    n=rs.getString("mov_name");
                    d=rs.getString("descr");
                    r=rs.getInt("rating");

                   model.addRow(new Object[]{m,n,d,r});
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Enter Movie Name !!!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        //jLabel6.setText("");
        //DefaultTableModel model=(DefaultTableModel) Table1.getModel();
         //model.setRowCount(0);
        //if(!mid.getText().trim().equals("")){
          //  model.addRow(new Object[]{mid.getText(),mname.getText(),descr.getText(),rating.getText()});
        //}else{
         //   jLabel6.setText("Movie id shold not be left blank");
        //}

    }//GEN-LAST:event_searchMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        mysqlconnector msq=new mysqlconnector();
        try {
            
            String mov_id=mid.getText();
            String mov_name=mname.getText();
            String descr=this.descr.getText();
            String rating=this.rating.getText();

            Connection con=msq.getConnection();
            
            PreparedStatement p=con.prepareStatement("select mov_name,mov_id from movie where mov_name='"+mov_name+"'");
            ResultSet r = p.executeQuery();
            
            if((r.next())&& !( mov_id.equals(r.getString("mov_id"))))
            {
                //if(mov_id.equals(r.getString("mov_id")));
                JOptionPane.showMessageDialog(this, "Movie is already Present", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            else
            {    
                PreparedStatement pst1=con.prepareStatement("Update Movie set mov_name=?,descr=?,rating=? where mov_id=?");
                pst1.setString(1, mov_name);
                pst1.setString(2, descr);
                pst1.setString(3, rating);
                pst1.setString(4, mov_id);

                if(pst1.executeUpdate()==1)
                {
                    JOptionPane.showMessageDialog(this, "UPDATED", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                     DefaultTableModel model=(DefaultTableModel) Table.getModel();
                   model.setRowCount(0);
                   //model.setRowCount(0);
                    showtabledata();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "FAILED", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
        }

     /*   jLabel6.setText("");
        DefaultTableModel model=(DefaultTableModel) Table1.getModel();
        if(Table1.getSelectedRow()==-1){
            if(Table1.getRowCount()==0){
                jLabel6.setText("Table is empty");
            }else{
                jLabel6.setText("You must select a movie");
            }
        }else{
            model.setValueAt(mid.getText(), Table1.getSelectedRow(),0);
            model.setValueAt(mname.getText(), Table1.getSelectedRow(), 1);
            model.setValueAt(descr.getText(), Table1.getSelectedRow(), 2);
            model.setValueAt(rating.getText(), Table1.getSelectedRow(), 3);
        }
        
*/
    }//GEN-LAST:event_updateMouseClicked

    private void delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delMouseClicked
        // TODO add your handling code here:
         mysqlconnector msq=new mysqlconnector();
         try {
            
            String mov_id=mid.getText();
            String mov_name=mname.getText();
            String descr=this.descr.getText();
            String rating=this.rating.getText();

            Connection con=msq.getConnection();
            
            PreparedStatement p=con.prepareStatement("delete from movie where mov_name='"+mov_name+"'");
            
            
           
                if(p.executeUpdate()==1)
                {
                    JOptionPane.showMessageDialog(this, "DELETED", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                     DefaultTableModel model=(DefaultTableModel) Table.getModel();
                   model.setRowCount(0);
                    showtabledata();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "FAILED", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            
        } catch (Exception e) {
        }

        
    }//GEN-LAST:event_delMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        //jLabel6.setText("");
        DefaultTableModel model=(DefaultTableModel) Table.getModel();
        
        mysqlconnector msq=new mysqlconnector();
        try {
            String mov_id=mid.getText();
            String mov_name=mname.getText();
            String descr=this.descr.getText();
            String rating=this.rating.getText();

            if(mov_id.equals("") || mov_name.equals("") || descr.equals("") || rating.equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please fill all the details", "INFO", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                int mid_len=mov_id.length();
                if(mid_len==3)
                {

                    Connection con=msq.getConnection();
                    PreparedStatement p=con.prepareStatement("select mov_id,mov_name from movie where mov_name='"+mov_name+"' or mov_id="+mov_id+";");
                    ResultSet r = p.executeQuery();

                    if(r.next())
                    {
                        JOptionPane.showMessageDialog(this, "Movie id/name already exists", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {  
                        //Connection con=msq.getConnection();
                        PreparedStatement pst1=con.prepareStatement("insert into Movie values(?,?,?,?)");
                        pst1.setString(1, mov_id);
                        pst1.setString(2, mov_name);
                        pst1.setString(3, descr);
                        pst1.setString(4, rating);

                        if(pst1.executeUpdate()==1)
                        {
                            model.addRow(new Object[]{mov_id,mov_name,descr,rating});
                            JOptionPane.showMessageDialog(this, "INSERTED", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                            model.setRowCount(0);
                            showtabledata();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "FAILED", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    
                                    
                }
                else
                {
                        JOptionPane.showMessageDialog(this, "Movie ID should be of 3 digits", "Message", JOptionPane.INFORMATION_MESSAGE);    
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_addMouseClicked

    private void back_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_lblMouseClicked
        // TODO add your handling code here:
         new adminhome(adm).setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_back_lblMouseClicked

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    private void midMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_midMouseClicked
        // TODO add your handling code here:
        
        mid.setText("");
        
    }//GEN-LAST:event_midMouseClicked

    private void mnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameMouseEntered

    private void mnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnameMouseClicked
        // TODO add your handling code here:
        mname.setText("");
    }//GEN-LAST:event_mnameMouseClicked

    private void descrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descrMouseClicked
        // TODO add your handling code here:
        descr.setText("");
    }//GEN-LAST:event_descrMouseClicked

    private void ratingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingMouseClicked
        // TODO add your handling code here:
        rating.setText("");
    }//GEN-LAST:event_ratingMouseClicked

    private void delradioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delradioMouseClicked
        // TODO add your handling code here:
       add.setVisible(false);
        update.setVisible(false);
        del.setVisible(true);
        search.setVisible(true);
    }//GEN-LAST:event_delradioMouseClicked

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        this.setState(adminhome.ICONIFIED);
    }//GEN-LAST:event_MinimizeActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        mysqlconnector msq=new mysqlconnector();
        try
        {
            Connection con=msq.getConnection();
            PreparedStatement pst=con.prepareStatement("update admin set admin_status=0 where admin_status=1;");

            //ResultSet rs=pst.executeQuery();
            if (pst.executeUpdate()==1)
            {
                JOptionPane.showMessageDialog(this, "Logging Out...", "Info", JOptionPane.INFORMATION_MESSAGE);
                new admin().setVisible(true);
                this.dispose();
            }
            else
            JOptionPane.showMessageDialog(this, "Something Went Wrong...", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_CloseActionPerformed

    private void ratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratingActionPerformed

    private void descrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descrActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel) Table1.getModel();
        mid.setText(model.getValueAt(Table1.getSelectedRow(), 0).toString());
        mname.setText(model.getValueAt(Table1.getSelectedRow(), 1).toString());
        descr.setText(model.getValueAt(Table1.getSelectedRow(), 2).toString());
        rating.setText(model.getValueAt(Table1.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_Table1MouseClicked

    private void searchradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchradioActionPerformed
        // TODO add your handling code here:
        if(searchradio.isSelected()==true)
        {
            searchradio.setSelected(true);
         del.setVisible(false);
        add.setVisible(false);
        update.setVisible(false);
        search.setVisible(true);
        
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(true);
        jSeparator3.setVisible(false);
        jSeparator4.setVisible(false);
        
        mid.setVisible(false);
        mname.setVisible(true);
        descr.setVisible(false);
        rating.setVisible(false);
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(true);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        }
    }//GEN-LAST:event_searchradioActionPerformed

    private void delradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delradioActionPerformed
        // TODO add your handling code here:
          if(delradio.isSelected()==true)
        {
            delradio.setSelected(true);
         del.setVisible(true);
        add.setVisible(false);
        update.setVisible(false);
        search.setVisible(false);
        
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(true);
        jSeparator3.setVisible(false);
        jSeparator4.setVisible(false);
        
        mid.setVisible(false);
        mname.setVisible(true);
        descr.setVisible(false);
        rating.setVisible(false);
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(true);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        }
    }//GEN-LAST:event_delradioActionPerformed

    private void Logout_LblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_LblMouseClicked
        mysqlconnector msq=new mysqlconnector();
        try
        {
            Connection con=msq.getConnection();
            PreparedStatement pst=con.prepareStatement("update admin set admin_status=0 where admin_status=1;");

            //ResultSet rs=pst.executeQuery();
            if (pst.executeUpdate()==1)
            {
                JOptionPane.showMessageDialog(this, "Logging Out...", "Info", JOptionPane.INFORMATION_MESSAGE);
                new admin().setVisible(true);
                        this.dispose();
            }
            else
            JOptionPane.showMessageDialog(this, "Something Went Wrong...", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_Logout_LblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminmovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_logo;
    private javax.swing.JButton Close;
    private javax.swing.JLabel Current_admin;
    private javax.swing.JLabel Logout_Lbl;
    private javax.swing.JButton Minimize;
    private javax.swing.JLabel SearchResultTable;
    private javax.swing.JTable Table;
    private javax.swing.JTable Table1;
    private javax.swing.JLabel Tableheading;
    private javax.swing.JLabel add;
    private javax.swing.JRadioButton addradio;
    private javax.swing.JLabel back_lbl;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel del;
    private javax.swing.JRadioButton delradio;
    private javax.swing.JTextField descr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField mname;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField rating;
    private javax.swing.JLabel search;
    private javax.swing.JRadioButton searchradio;
    private javax.swing.JLabel update;
    private javax.swing.JRadioButton updateradio;
    // End of variables declaration//GEN-END:variables
}
