/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hello;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javafx.beans.binding.Bindings;
import javax.swing.JOptionPane;

/**
 *
 * @author Hello India
 */
public class SignupTest extends javax.swing.JFrame {

    /**
     * Creates new form SignupTest
     */
    public SignupTest() {
        initComponents();
        user_name.setText("");
        user_id.setText("");
        user_pwd.setText("");
        mob_no.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        CheckBoxShowPwd = new javax.swing.JCheckBox();
        CloseLbl = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        user_pwd = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mob_no = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSignin = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        CheckBoxShowPwd.setText("Show Password");
        CheckBoxShowPwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckBoxShowPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxShowPwdActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBoxShowPwd);
        CheckBoxShowPwd.setBounds(270, 280, 120, 29);

        CloseLbl.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        CloseLbl.setForeground(new java.awt.Color(153, 153, 153));
        CloseLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLbl.setText("X");
        CloseLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseLbl.setMaximumSize(new java.awt.Dimension(30, 30));
        CloseLbl.setMinimumSize(new java.awt.Dimension(30, 30));
        CloseLbl.setPreferredSize(new java.awt.Dimension(30, 30));
        CloseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLblMouseExited(evt);
            }
        });
        getContentPane().add(CloseLbl);
        CloseLbl.setBounds(570, 0, 30, 30);

        user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_idActionPerformed(evt);
            }
        });
        getContentPane().add(user_id);
        user_id.setBounds(270, 210, 200, 30);

        user_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_pwdActionPerformed(evt);
            }
        });
        getContentPane().add(user_pwd);
        user_pwd.setBounds(270, 250, 200, 30);

        btnSignup.setBackground(new java.awt.Color(200, 0, 50));
        btnSignup.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("SIGN UP");
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup);
        btnSignup.setBounds(270, 390, 100, 35);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("EMAIL ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 210, 100, 30);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 250, 100, 30);

        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        getContentPane().add(user_name);
        user_name.setBounds(270, 170, 200, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("USERNAME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 170, 100, 30);

        mob_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mob_noActionPerformed(evt);
            }
        });
        getContentPane().add(mob_no);
        mob_no.setBounds(270, 310, 200, 30);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("MOBILE NO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 310, 100, 30);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel7.setText("A World of");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(161, 93, 104, 33);

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("Entertainment Awaits");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(271, 95, 207, 28);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Already connected ?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(122, 459, 200, 30);

        btnSignin.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnSignin.setForeground(new java.awt.Color(153, 0, 51));
        btnSignin.setText("Sign In");
        btnSignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignin);
        btnSignin.setBounds(326, 461, 73, 27);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void user_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_pwdActionPerformed

    private void user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_idActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
         mysqlconnector msq=new mysqlconnector();
        try {
            Connection con = msq.getConnection();
            
            String uname=user_name.getText();
            PreparedStatement pst1=con.prepareStatement("select user_name from user where user_name='"+uname+"';");
            ResultSet rs1=pst1.executeQuery();
            
            if(rs1.next())
                {
                    JOptionPane.showMessageDialog(this, "Username Already Exist", "Error", JOptionPane.ERROR_MESSAGE);
                    user_name.setText("");
                    user_id.setText("");
                    user_pwd.setText("");
                    mob_no.setText("");
                }
            else
            {

                if( uname.equals("") || user_id.getText().equals("") || String.valueOf(user_pwd.getPassword()).equals("")|| mob_no.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(this, "Please Fill all the details", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                    
                else
                {
                    boolean status=Validate.validateEmail(user_id.getText());
                    if(status)
                    {
                        int moblen=0;
                        moblen=mob_no.getText().length();
                        
                        if(moblen==10)
                        {
                        
                            PreparedStatement pst=con.prepareStatement("insert into user values(?,?,?,?,?);");
                            pst.setString(1,user_name.getText());
                            pst.setString(2,user_id.getText());
                            pst.setString(3,String.valueOf(user_pwd.getPassword()));
                            //pst.setString(3,user_pwd.getText());
                            pst.setString(4,mob_no.getText());
                            pst.setString(5,"0");



                            if(pst.executeUpdate()==1)
                            {
                                JOptionPane.showMessageDialog(this, "Successfully Signed Up !!!", "Info", JOptionPane.INFORMATION_MESSAGE);
                                new LoginTest().setVisible(true);
                                this.dispose();
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(this, "User already Exist", "Info", JOptionPane.ERROR_MESSAGE);    
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "Incorrect Mobile No.(Enter 10 Digits)", "Info", JOptionPane.ERROR_MESSAGE);
                        }
                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Not valid Email id", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSignupActionPerformed

    private void mob_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mob_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mob_noActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        // TODO add your handling code here:
        new LoginTest().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSigninActionPerformed

    private void CloseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLblMouseClicked
        /*mysqlconnector msq1=new mysqlconnector();
        try
        {
            Connection con1= msq1.getConnection();
            PreparedStatement pst1=con1.prepareStatement("update user set user_status=0 where user_status=1;");
            pst1.executeUpdate();
        }
        catch(Exception e)
        {}*/
        this.dispose();
    }//GEN-LAST:event_CloseLblMouseClicked

    private void CloseLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLblMouseEntered
        CloseLbl.setForeground(Color.WHITE);
    }//GEN-LAST:event_CloseLblMouseEntered

    private void CloseLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLblMouseExited
        CloseLbl.setForeground(Color.GRAY);
    }//GEN-LAST:event_CloseLblMouseExited

    private void CheckBoxShowPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxShowPwdActionPerformed
        if(CheckBoxShowPwd.isSelected()){
            user_pwd.setEchoChar((char)0);
        }
        else{
            user_pwd.setEchoChar('*');
        }
    }//GEN-LAST:event_CheckBoxShowPwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxShowPwd;
    private javax.swing.JLabel CloseLbl;
    private javax.swing.JButton btnSignin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mob_no;
    private javax.swing.JTextField user_id;
    private javax.swing.JTextField user_name;
    private javax.swing.JPasswordField user_pwd;
    // End of variables declaration//GEN-END:variables
}
